spring:

  web:
    # 静态资源处理
    resources:
      # 启动静态资源处理
      add-mappings: true
      chain:
        # 资源链启动缓存，默认启动
        cache: true
        # 启用资源链，默认禁用
        enabled: true
        # 启动压缩资源(gzip,brotli)解析，默认禁用
        compressed: true
        # html-application-cache: true 不推荐使用

      cache:
        cachecontrol:
          # 缓存相应时间 单位秒
          max-age: 3600
      static-locations: classpath:/static/



  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: MySQL122590
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认600000(10分钟)
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间，默认30000(30秒)
      connection-timeout: 3000
      # 检验连接有效性
      connection-test-query: SELECT 1

  redis:
    # 服务器地址
    host: 192.168.134.133
    # 端口
    port: 6379
    # 密码
    password: 123qwe
    # 数据库
    database: 0
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数 默认8
        max-active: 8
        # 最大连接阻塞时间
        max-wait: 1000ms
        # 最大空闲连接，默认8
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5


  # RabbitMQ
  rabbitmq:
    # 服务器
    host: 192.168.134.133
    # 用户名
    username: onion
    # 密码
    password: 123qwe
    # 虚拟主机
    virtual-host: /
    # 端口号
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只能处理一条消息，处理完毕再继续下一条消息
        prefetch: 1
        # 启动时是否默认启动容器，默认true
        auto-startup: true
        # 被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认false
        enabled: true
        # 重试时间，默认1000ms
        initial-interval: 1000ms
        # 重试最大次数，默认3次
        max-attempts: 3
        # 重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        # 重试的间隔系数，比如配2.0，第一次10s，第二次就20s，第三次40s
        multiplier: 1


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.gunjo.skilldemo.pojo

logging:
  level:
    com.gunjo.skilldemo.mapper: debug