spring:

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: MySQL122590
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接最大存活时间，默认600000(10分钟)
      idle-timeout: 1800000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间，默认30000(30秒)
      connection-timeout: 3000
      # 检验连接有效性
      connection-test-query: SELECT 1

  redis:
    # 服务器地址
    host: 192.168.134.133
    # 端口
    port: 6379
    # 密码
    password: 123qwe
    # 数据库
    database: 0
    # 超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数 默认8
        max-active: 8
        # 最大连接阻塞时间
        max-wait: 1000ms
        # 最大空闲连接，默认8
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5



#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.gunjo.skilldemo.pojo

logging:
  level:
    com.gunjo.skilldemo.mapper: debug